### ISSUE TITLE
Safe Account WalletConnect - issue in creating, signing and executing Txs

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1479]
Note - I originally logged this as an issue in PR 1465 here - https://github.com/decentdao/fractal-interface/pull/1465#issuecomment-2012176234

See the below the test suite of failures I had in the above PR netlify AND app.dev AND production app

https://github.com/decentdao/fractal-interface/pull/1465#issuecomment-2012176234

Multisig

1) create a safe - PARTIAL SUCCESS - initally safe app said 'failed - untrusted transaction as a toaster'.... then weirdly it went through got this link - https://app.safe.global/transactions/tx?id=multisig_0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5_0x845eeb01cff0891edb9cbc306bfc6f6cb64c513033cd02c8b1f83ebcba96f1de&safe=sep:0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5

2)create a proposal - failed twice - for changing name and adding a signer - https://app.safe.global/transactions/messages?safe=sep:0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5
Screenshot 2024-03-21 at 12 09 44
--> here's the safe with the issues - https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0xa719FcC542a59A6C52b4C482e562334bF1aF9828

3) sign transaction - it said success in fractal and safe app but no signature actually made to pass transatciont. https://app.safe.global/transactions/messages?safe=sep%3A0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5 ? --> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x652A8159eCc60F63589FbE35FBDa0E77679BA70E/proposals/0x0f6d35d0da46b120f26aee9d853d198a21ae1d28ae7763dc26c10caf409f1119

Since then I tried testing a new multisig to treble check the issue

- Tried creating a multisig with WC here via the Fractal App

-The tx went through here - https://app.safe.global/transactions/history?safe=sep:0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5. 

- Yet in the app it got stuck on this screen 

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/ce21f364-b6ed-4dda-b789-be7e6cb382be)

**Comment by Da-Colon** [comment]
So let me tell you about the journey I went on...

- Checked Wallet Connection ✅ 
- Checked Workflow code ✅ 
- Checked Safe Creation works via wallet connect ✅ 
- Safe to Safe wallet connect transaction works ✅ 
- Went back to previous versions of the app all the way back to nextJS and its not still not working ✅ 
  - This is where it got weird...I've definitely tested Multisig via wallet connect since then. and it WAS working ❌ 
- Next checked for any recent changes.....Switch to L2...okay...what if its contract types are different or something... I went and pulled down the safe contracts (luckly most recent branch has typechain). set it to v5 ethers and grab those files.
  - Went and replaced GnosisSafeL2__factory -> SafeL2__factory....and.... ❌ 
- Attempted to replace ethers `signer` with wagmi's `walletClient` BIG ❌ 
  - This broke Safe screen. In thier console said invalid value for 'address', value = null....What?
- Reviewed documentation on typedSignData, EIP-712, EIP-1271. We are following the right procedures as far as I can tell ✅ 
- checked documentation on Safe API and Safe Kit...
  - This could be a solution potentially using its `proposeTransaction` method. ❓ 


The only other option is that Safe has very recently changed something that has made our end incompatible....

**Comment by tomstuart123** [comment]
@Da-Colon / @adamgall / @mudrila I haven't seen this issue again since I first raised it. Anyone else have any latest?

 do we know if this got closed by a prior PR? Or does this get closed by current ethers work?

Just trying to work out if this is the right column for this?

**Comment by adamgall** [comment]
> @Da-Colon / @adamgall / @mudrila I haven't seen this issue again since I first raised it. Anyone else have any latest?
> 
> do we know if this got closed by a prior PR? Or does this get closed by current ethers work?
> 
> Just trying to work out if this is the right column for this?

@tomstuart123 I haven't experienced this. If the testing that caused you to open this issue, now works as expected, then we can close this issue.

**Comment by Da-Colon** [comment]
I think I remember what this was. Despite the name (I'll update this now). This was when connected to a Multisig Safe via WalletConnect and then interacting with the Fractal App. So the workflow to see if this is still a problem

- Connect to a Safe Account via WalletConnect
- Create DAOs (Azorious or Multisig)

When trying to sign transaction an error occurs that the signature created comes back as a different address when verified by Safe when posting the signed Tx to Safe's API.

**Comment by adamgall** [comment]
Closing this issue, haven't had complaints about it in a while.
