### ISSUE TITLE
Automatic keyboard appearance

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1878]
@decentdao/engineering When clicking the Safe name search input on mobile home, can you bring the keyboard up automatically when the user presses the input? Currently I have to click the input twice to bring the keyboard up.

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524425_

**Comment by Da-Colon** [comment]
Spoke with @adamgall and @nicolaus-sherrill about the problems with the current setup and Mobile Browsers.

The TL:DR is that mobile browsers seem to allow for autofocus (needed since we are popping up the search input in a modal) from pulling up the mobile keyboard. 

Discussed other options that will be taken back to design before code is changed.

**Comment by tomstuart123** [comment]
@adamgall / @Da-Colon does your TLDR above mean that this autofocus should be doable by dev? Or that design is needed first

**Comment by adamgall** [comment]
> @adamgall / @Da-Colon does your TLDR above mean that this autofocus should be doable by dev? Or that design is needed first

With our current understanding of the issue and it's cause, this isn't "fixable" by engineering.

IMO the best time/place to fix this issue would be to revisit it if/when the search UX is overhauled.

@tomstuart123 My suggestion is that we close this issue for now.

**Comment by tomstuart123** [comment]
agreed. close
