### ISSUE TITLE
Replace loading indicator

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1965]
Use the following animation in place of the current 3-bar loading animation:

https://codepen.io/ruigewaard/pen/dyKZYQ

**Comment by DarksightKellar** [comment]
I uh ... I think this is a bit much:

<img width="217" alt="Screenshot 2024-05-31 at 11 31 49" src="https://github.com/decentdao/decent-interface/assets/7101382/baf8cd63-fcd0-47fe-9f4c-1b7af13cc1c1">

I agree with instead using the logo is _some_ form.

Or just ... not changing what already looks totally fine?

**Comment by adamgall** [comment]
@nicolaus-sherrill please run a design cycle on this and make sure it's integrated into Figmas before engineering spends time on it.

**Comment by xanaramoss** [comment]
We don't have an animated logomark.
We tried a bunch of versions but nothing passed. 

I agree with @DarksightKellar the one above looks a bit too much. 
I can look at some options, but I prefer the current one than [this one. ](https://codepen.io/ruigewaard/pen/dyKZYQ)

**Comment by tomstuart123** [comment]
Nice , @xanaramoss . Excited to get your take rest of @decentdao/design 

This also has potential to be picked up now we have more progress on hats

**Comment by adamgall** [comment]
when @decentdao/design has agreed on one of the options, we can move this to `Ready`

**Comment by nicolaus-sherrill** [comment]
@decentdao/engineering @xanaramoss The point of this issue was to get a quick change to the element preloader per Parker's request with something else already created before doing anything more custom.

Suggest implementation of the original suggestion would be using a white alpha 4% color so that it would be very subtle over the cards. If others have suggestions of alternatives to swap in, I'm open to them, but Parker wants a change here.

My _preferred_ custom solution would be to display an empty state of loading elements with a glare moving across the element (check youtube on a poor connection mobile for reference of this type of pattern), but that is going to take more work than swapping something stock.

**Comment by xanaramoss** [comment]
> @decentdao/engineering @xanaramoss The point of this issue was to get a quick change to the element preloader per Parker's request with something else already created before doing anything more custom.
> 
> Suggest implementation of the original suggestion would be using a white alpha 4% color so that it would be very subtle over the cards. If others have suggestions of alternatives to swap in, I'm open to them, but Parker wants a change here. <img alt="Screenshot 2024-06-13 at 10 39 14 AM" width="231" src="https://private-user-images.githubusercontent.com/62394931/339444690-a47ab4fa-3e80-44b7-9a38-4c74963fb5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzIwMzYsIm5iZiI6MTcxODM3MTczNiwicGF0aCI6Ii82MjM5NDkzMS8zMzk0NDQ2OTAtYTQ3YWI0ZmEtM2U4MC00NGI3LTlhMzgtNGM3NDk2M2ZiNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOWZmZDMxZjZlMWQwMTVmMTNiZjdiZjFhNDk1NDFkNmFkOTM0OTM2YzdiNmI5NWFiNDFhOGZmOWZlMTkwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3xry-JLVfVveUUFKq56736IFIxGNEw9ZBG_UMwXhUEI">
> 
> The ask was something more appropriate to the brand identity and _much_ more subtle than the current three growing/shrinking bar design.
> 
> If we are going to produce something custom, my _preferred_ solution would be to display an empty state of loading elements with a glare moving across the element (check youtube on a poor connection mobile for reference of this type of pattern), but that is going to take more work than swapping something stock.

@nicolaus-sherrill thanks for the context!
With the alpha I think that one might work hell. What about the one I did but with Alpha? Is it too much? It is because it's a repetitive element it might be too distracting with the circular movement?

For sure I can create one with your suggestion, but I need more visual cues before animating. Is this what you are referring too?

<img width="103" alt="Screenshot 2024-06-14 at 15 35 26" src="https://github.com/decentdao/decent-interface/assets/162434678/4bd74371-3995-4c4f-9487-ee538b09497f">

**Comment by nicolaus-sherrill** [comment]
> For sure I can create one with your suggestion, but I need more visual cues/references before animating. [Something like this?](https://lottiefiles.com/animations/quick-access-loading-animation-qPKcrzoX7g)

Yes, exactly, something like that! Per standups last week, engineering believes implementing it won't be too big of a lift. I think we also have additional design responsibility to create empty-state designs of components that are loaded in this way to handoff to ENG as part of this work.

Tom and I are going to discuss design backlog tomorrow and prioritize items, with this top-of-mind.
