### ISSUE TITLE
Testing blocker - assets not loaded to netlify stream or treasury pages

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#2192]
@decentdao/engineering - I've faced this issue a tonne but only created an issue ages ago when we though it was moralis credits. Not sure that's the case so going to re-raise

TLDR --> Treasury (e.g. [this one](https://deploy-preview-2187.app.dev.decentdao.org/treasury?dao=sep:0x7bABf83D1836DFB0eEAADF697cAb8A7ebDc2cE5E)) won't show assets correctly when on netlfiy (see right hand column)

<img width="1198" alt="Screenshot 2024-07-31 at 10 12 04" src="https://github.com/user-attachments/assets/3e1a9957-e0de-4d26-84ae-0acce655fb53">

Impact --> it means assets that exist in treasury won't get pulled into streams page. No assets appaer when the 'Roles' Token should appear
<img width="469" alt="Screenshot 2024-07-31 at 10 13 24" src="https://github.com/user-attachments/assets/c15d3d61-f43c-4a31-b39a-f4b9655631e0">

Where --> this always happens on netlify. On production it always works ([same treasury works here](https://app.decentdao.org/treasury?dao=sep:0x7bABf83D1836DFB0eEAADF697cAb8A7ebDc2cE5E)) and on dev it seems sometimes works, sometimes not
<img width="1190" alt="Screenshot 2024-07-31 at 10 18 03" src="https://github.com/user-attachments/assets/47e13e87-177e-4a28-a2b7-4110274aad59">

Consistency --> it's weird. It always happens when I first setup a multisig to test and send assets to it. I know the assets are there from sepolia scan/our production app. Then after a few hours it seems to appear. Not great for my testing though as sometimes I only have certain slots in the day to unblock y'all

**Comment by adamgall** [comment]
My assumption is that when a Safe is first created, it takes a few minutes for Moralis to index it. Before it's indexed, we make our first request to Moralis for token data. That request returns no data, but we nonetheless mark the request as successful (because technically it was), and then our own delay mechanism kicks in which means we won't query Moralis for this data again until `BALANCES_CACHE_INTERVAL_MINUTES` expires.

https://github.com/decentdao/decent-interface/blob/develop/netlify/functions/tokenBalances.mts#L92-L95

As a "fix" (with some tradeoffs that I think are acceptable), let's only mark the request as successful (`tokensFetched = true`) if we get token data back from Moralis.

The tradeoff will be that if there's an actual DAO Safe that has zero tokens, we'll always re-request data from Moralis on each Netlify request, which might not be ideal.

We _could_ add some more logic into this behavior, which tracks the _first time_ a request is made, and only keep re-requesting from Moralis if we're within, say, 5 minutes from the first time we tried to get data. I actually think I like this solution. No risky tradeoffs in this scenario. I assume 5 mins will be enough time for Moralis to index, but we could always tweak that number.
