### ISSUE TITLE
"Organization" page seems broken

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#2458]
On production, trying to load Myosin's "Organization" page results in an ungodly amount of console errors, and it doesn't load.

https://app.decentdao.org/hierarchy?dao=base:0x374D5a17D2433415C48C735A493F0523DaB99041

Is this only a problem on Base? Is it only a problem with Myosin's DAO?

Is it related to https://github.com/decentdao/decent-interface/issues/2347?

What's going on here?

**Comment by mudrila** [comment]
@adamgall This one is fixed, right?

**Comment by Da-Colon** [comment]
Yeah @DarksightKellar and I were exploring the loading issue some more. Narrowed the issues to:

- Signal Abort: Caused by multiple requests or a not ready apollo client.
- component re-rerendering; UseEffect dependencies

replacing the two useEffect dependency arrays with empty array and ignoring the warning. makes the useEffect only fire once and 'fixes' things. draft till I or @DarksightKellar can circle back to it. and drill into it further.

There is another fix for #2398 in that PR that I'll extract to its own PR.
