### ISSUE TITLE
add more socials

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2545]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc280229892c0d678980b3e

**Comment by nicolaus-sherrill** [comment]
@decentdao/engineering updates here:
https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.1.1?m=auto&node-id=2815-13056

Please note, there were some changes to the spacing of the button pills to the left of the endorsement
<img width="592" alt="Screenshot 2024-11-22 at 1 54 59 PM" src="https://github.com/user-attachments/assets/490e7b18-30bc-470b-8e9f-c53f48105895">

On mobile, I haven't yet nudged over those pills like they are on prod, so the only thing that needs to change there is the spacing between the elements and their order in the footer:
<img width="386" alt="Screenshot 2024-11-22 at 1 56 38 PM" src="https://github.com/user-attachments/assets/8a22a4e2-ee6b-499d-8827-9b9c1f4d5c41">

In addition, this update to the footer makes one additional change to the left side nav, removing the Warpcast link from there since it is now in the footer with the other socials:
<img width="475" alt="Screenshot 2024-11-22 at 1 57 42 PM" src="https://github.com/user-attachments/assets/2466eb7f-ce77-4fa8-b894-a8d80cb1e64b">

**Comment by nicolaus-sherrill** [comment]
Hey @DarksightKellar the text sizes on the Footer are all over the place. Could you please update them all to be `labels.large`? That is what is spec'd in designs.

**Comment by Da-Colon** [comment]
closed.
